### ISSUE TITLE
xcode 8 : Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by Sivabalaa** [techquest/isw-payment-sdk-ios#17]
When i open demo xcode project in xcode v.8.0, we are facing error like

CompileSwift normal i386 /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/CardDemo/ViewController.swift
    cd /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo
    /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/CardDemo/ViewController.swift /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/CardDemo/AppDelegate.swift -target i386-apple-ios9.3 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -I /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator -F /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator -F /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator/Alamofire -F /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator/CryptoSwift -F /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator/SwiftyJSON -F /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo -enable-testing -g -module-cache-path /Users/developer/Library/Developer/Xcode/DerivedData/ModuleCache -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/CardDemo-generated-files.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/CardDemo-own-target-headers.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/CardDemo-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/CardDemo-project-headers.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/Pods/Headers/Public -Xcc -I/Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/Pods/Headers/Public/OpenSSL -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/DerivedSources/i386 -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -working-directory/Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo -emit-module-doc-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController~partial.swiftdoc -Onone -module-name CardDemo -emit-module-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController~partial.swiftmodule -serialize-diagnostics-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController.dia -emit-dependencies-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController.d -emit-reference-dependencies-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController.swiftdeps -o /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController.o

0  swift                    0x00000001056c676b llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 43
1  swift                    0x00000001056c5a56 llvm::sys::RunSignalHandlers() + 70
2  swift                    0x00000001056c6dbf SignalHandler(int) + 287
3  libsystem_platform.dylib 0x00007fffe51fdbba _sigtramp + 26
4  libsystem_platform.dylib 0x00007fe03d0ec601 _sigtramp + 1475275361
5  swift                    0x000000010362e918 swift::ModuleFile::getType(llvm::Fixnum<31u, unsigned int>) + 872
6  swift                    0x000000010362b2fa swift::ModuleFile::getDecl(llvm::Fixnum<31u, unsigned int>, llvm::Optional<swift::DeclContext*>) + 15690
7  swift                    0x0000000103627475 swift::ModuleFile::readParameterList() + 229
8  swift                    0x000000010362bb49 swift::ModuleFile::getDecl(llvm::Fixnum<31u, unsigned int>, llvm::Optional<swift::DeclContext*>) + 17817
9  swift                    0x0000000103632239 swift::ModuleFile::readMembers(llvm::SmallVectorImpl<swift::Decl*>&) + 249
10 swift                    0x000000010363477e swift::ModuleFile::loadAllMembers(swift::Decl*, unsigned long long) + 206
11 swift                    0x000000010396bc5c swift::NominalTypeDecl::getMembers(bool) const + 28
12 swift                    0x00000001039a7b60 swift::NominalTypeDecl::lookupDirect(swift::DeclName, bool) + 96
13 swift                    0x00000001039a6019 swift::DeclContext::lookupQualified(swift::Type, swift::DeclName, unsigned int, swift::LazyResolver*, llvm::SmallVectorImpl<swift::ValueDecl*>&) const + 3241
14 swift                    0x0000000103887bb6 swift::TypeChecker::lookupMember(swift::DeclContext*, swift::Type, swift::DeclName, swift::OptionSet<swift::NameLookupFlags, unsigned int>)::$_1::operator()() const + 262
15 swift                    0x0000000103887a6a swift::TypeChecker::lookupMember(swift::DeclContext*, swift::Type, swift::DeclName, swift::OptionSet<swift::NameLookupFlags, unsigned int>) + 362
16 swift                    0x00000001037c42f1 swift::constraints::ConstraintSystem::lookupMember(swift::Type, swift::DeclName) + 241
17 swift                    0x000000010381557c swift::constraints::ConstraintSystem::performMemberLookup(swift::constraints::ConstraintKind, swift::DeclName, swift::Type, swift::constraints::ConstraintLocator*) + 1980
18 swift                    0x0000000103816ce5 swift::constraints::ConstraintSystem::simplifyMemberConstraint(swift::constraints::Constraint const&) + 373
19 swift                    0x0000000103817fe9 swift::constraints::ConstraintSystem::simplifyConstraint(swift::constraints::Constraint const&) + 281
20 swift                    0x00000001037c4adc swift::constraints::ConstraintSystem::addConstraint(swift::constraints::Constraint*, bool, bool) + 28
21 swift                    0x000000010380443a (anonymous namespace)::ConstraintGenerator::addMemberRefConstraints(swift::Expr*, swift::Expr*, swift::DeclName) + 218
22 swift                    0x0000000103800ccb (anonymous namespace)::ConstraintWalker::walkToExprPost(swift::Expr*) + 59
23 swift                    0x0000000103901f5c swift::Expr::walk(swift::ASTWalker&) + 76
24 swift                    0x00000001037fae2d swift::constraints::ConstraintSystem::generateConstraints(swift::Expr*) + 189
25 swift                    0x000000010384ed0e swift::TypeChecker::solveForExpression(swift::Expr*&, swift::DeclContext*, swift::Type, swift::FreeTypeVariableBinding, swift::ExprTypeCheckListener*, swift::constraints::ConstraintSystem&, llvm::SmallVectorImpl<swift::constraints::Solution>&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 270
26 swift                    0x0000000103855aee swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::Type, swift::ContextualTypePurpose, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::ExprTypeCheckListener*) + 542
27 swift                    0x0000000103856a54 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*) + 100
28 swift                    0x00000001038573cf swift::TypeChecker::typeCheckStmtCondition(llvm::MutableArrayRef<swift::StmtConditionElement>&, swift::DeclContext*, swift::Diag<>) + 543
29 swift                    0x00000001038a79c0 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 880
30 swift                    0x00000001038a777f swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 303
31 swift                    0x00000001038a7328 swift::TypeChecker::typeCheckClosureBody(swift::ClosureExpr*) + 216
32 swift                    0x00000001037cee2b swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::Expr*, swift::Type, bool, bool, bool) + 811
33 swift                    0x0000000103855b71 swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::Type, swift::ContextualTypePurpose, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::ExprTypeCheckListener*) + 673
34 swift                    0x00000001038a7802 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 434
35 swift                    0x00000001038a7967 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 791
36 swift                    0x00000001038a777f swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 303
37 swift                    0x00000001038a641f swift::TypeChecker::typeCheckFunctionBodyUntil(swift::FuncDecl*, swift::SourceLoc) + 335
38 swift                    0x00000001038a6c7a swift::TypeChecker::typeCheckAbstractFunctionBody(swift::AbstractFunctionDecl*) + 154
39 swift                    0x000000010383ec76 typeCheckFunctionsAndExternalDecls(swift::TypeChecker&) + 166
40 swift                    0x000000010383f735 swift::performTypeChecking(swift::SourceFile&, swift::TopLevelContext&, swift::OptionSet<swift::TypeCheckingFlags, unsigned int>, unsigned int) + 1397
41 swift                    0x00000001036c82d5 swift::CompilerInstance::performSema() + 3429
42 swift                    0x0000000103217ed0 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 944
43 swift                    0x0000000103216c79 frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2777
44 swift                    0x0000000103212765 main + 1957
45 libdyld.dylib            0x00007fffe4ff0255 start + 1
46 libdyld.dylib            0x000000000000004f start + 453049851
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/CardDemo/ViewController.swift /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/CardDemo/AppDelegate.swift -target i386-apple-ios9.3 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -I /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator -F /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator -F /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator/Alamofire -F /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator/CryptoSwift -F /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator/SwiftyJSON -F /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo -enable-testing -g -module-cache-path /Users/developer/Library/Developer/Xcode/DerivedData/ModuleCache -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/CardDemo-generated-files.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/CardDemo-own-target-headers.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/CardDemo-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/CardDemo-project-headers.hmap -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/Pods/Headers/Public -Xcc -I/Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/Pods/Headers/Public/OpenSSL -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/DerivedSources/i386 -Xcc -I/Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -working-directory/Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo -emit-module-doc-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController~partial.swiftdoc -Onone -module-name CardDemo -emit-module-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController~partial.swiftmodule -serialize-diagnostics-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController.dia -emit-dependencies-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController.d -emit-reference-dependencies-path /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController.swiftdeps -o /Users/developer/Library/Developer/Xcode/DerivedData/CardDemo-dvwzuwifflcsosdtwszixhwgbwmk/Build/Intermediates/CardDemo.build/Debug-iphonesimulator/CardDemo.build/Objects-normal/i386/ViewController.o 
1.	While type-checking 'pay' at /Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/CardDemo/ViewController.swift:139:5
2.	While type-checking expression at [/Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/CardDemo/ViewController.swift:148:13 - line:180:14] RangeText="sdk.purchase(request, completionHandler:{(purchaseResponse: PurchaseResponse?, error: NSError?) in
                guard error == nil else {
                    UIApplication.sharedApplication().networkActivityIndicatorVisible = false
                    self.activityIndicator.stopAnimating()
                    self.showError((error?.localizedDescription)!)
                    return
                }
                
                guard let response = purchaseResponse else {
                    UIApplication.sharedApplication().networkActivityIndicatorVisible = false
                    self.activityIndicator.stopAnimating()
                    self.showError((error?.localizedFailureReason)!)
                    return
                }
                
                guard let responseCode = response.responseCode else {
                    UIApplication.sharedApplication().networkActivityIndicatorVisible = false
                    self.activityIndicator.stopAnimating()
                    self.showSuccess("Ref: " + response.transactionIdentifier)
                    return
                }
                
                if responseCode == PaymentSDK.SAFE_TOKEN_RESPONSE_CODE {
                    self.handleOTP(response.message, authData: request.authData, purchaseResponse: response)
                } else if (responseCode == PaymentSDK.CARDINAL_RESPONSE_CODE) {
                    UIApplication.sharedApplication().networkActivityIndicatorVisible = false
                    self.activityIndicator.stopAnimating()
                    self.handleCardinal(request.authData, purchaseResponse: response)
                } else {
                    UIApplication.sharedApplication().networkActivityIndicatorVisible = false
                    self.activityIndicator.stopAnimating()
                }
            })"
3.	While type-checking expression at [/Users/developer/Desktop/isw-payment-sdk-ios-master/SampleCode/PaymentWithoutUi/CardDemo/CardDemo/ViewController.swift:163:42 - line:163:51] RangeText="response.r"
4.	While loading members for 'PurchaseResponse' at <invalid loc>
5.	While deserializing 'init' (ConstructorDecl #494) 
6.	While deserializing decl #2036 (PARAM_DECL)

Kindly check the same and update asap.

**Comment by alexcrownus** [comment]
The project should be opened with the XCode version stated in the documentation.
Closing this issue
