### ISSUE TITLE
Interswitch payment gateway pod file issue

### ISSUE THREAD

**Issue by NiteshKhandal** [techquest/isw-payment-sdk-ios#24]
i have install pod using below code:
use_frameworks!

pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git', :tag => '0.6.9'
 pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.4.0'
 pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :tag => '3.1.4'
 pod 'OpenSSL-Universal', '1.0.2.10'
 

But i am facing a problem as below:
"Module compiled with swift 3.1 cannot be imported in swift 3.0.2."

**Comment by tobzy** [comment]
Upgrade your Xcode to 8.3 and your Swift version should be 3.1
run in terminal 'xcrun swift -version' to determine current version.

**Comment by ravifullestop** [comment]
My xcode version is Xcode 8.3 and Swift version 3.1. Its still not working.

**Comment by tobzy** [comment]
You might need to recompile one or more of the third-party modules. Please take a look at this if you are still getting the same error.  [(https://stackoverflow.com/questions/40250381/module-compiled-with-swift-3-0-cannot-be-imported-in-swift-3-0-1?rq=1]. If however, you are getting a different error, let me see your error logs.

**Comment by venkatesh513** [comment]
I'm using Swift 3.1 and Xcode 8.3.2

After installing pod file, It is showing link error command after that i have imported
Below .h files into bridging header
#import <PaymentSDK/PaymentSDK-Swift.h>
#import <PaymentSDK/Crypto.h>
#import <PaymentSDK/PaymentSDK.h>

After that sometimes working properly and sometimes showing link error command i don't know 
what is going on really but if i use sdk with obj c everything working fine...
I'm facing problems with only Swift

**Comment by venkatesh513** [comment]
please give perfect answer

**Comment by venkatesh513** [comment]
And also showing any Payment methods

**Comment by SathishHTS** [comment]
After succeeding with the Interswitch test card payment I getting null response in token, tokenExpiryDate and transactionRef.

Responses are,
transactionIdentifier=FBN|API|MX187|29-05-2018|242894|627846, message=Approved by Financial Institution, amount=666.00, token=(null), tokenExpiryDate=(null), panLast4Digits=(null) transactionRef=nyZ5roZvnttH

Test card Details:
Successful Transaction Verve Test Card (No OTP)
5061030000000000084
Sept 2019
1234
123

Kindly give me any solution for this issue.
Thank you.
