### ISSUE TITLE
Update to Swift 3.2 to accommodate Xcode 9.1

### ISSUE THREAD

**Issue by rbmutai** [techquest/isw-payment-sdk-ios#30]
Please update the framework to swift 3.2. As you know, in the current Xcode version 9.1, the minimum swift version is 3.2. So it is not possible to use the interswitch payment sdk for iOS. Kindly update it.

**Comment by ajinkyashelar** [comment]
Yes, please we need an updated version of the iOS SDK asap as we are restricted to use the older version of Xcode just for the dependency of this Payment framework. 

Please work towards keeping the SDK up to date.

**Comment by rockinrohit92** [comment]
For Swift 3.2, use https://github.com/AyoGitNg/isw-payment-sdk-ios/releases/tag/v.0.0.0.3
