### ISSUE TITLE
Compatibility with Swift 4

### ISSUE THREAD

**Issue by ItexIntegrated** [techquest/isw-payment-sdk-ios#31]
Hi, I am currently working on an iOS application with Swift 4.0.3. I am trying to integrate the payment sdk into the application, but I get a '''Module compiled with Swift 2.3 cannot be imported in Swift 4.0.3:''' error.

**Comment by rockinrohit92** [comment]
https://github.com/AyoGitNg/isw-payment-sdk-ios/releases/tag/v.0.0.0.4

**Comment by ItexIntegrated** [comment]
Thanks a lot.
