### ISSUE TITLE
Swift 4 PaymentSDK : cannot find the swift declaration for this class,  Xcode 9.2 compatible build pls.

### ISSUE THREAD

**Issue by rockinrohit92** [techquest/isw-payment-sdk-ios#32]
Contacted Support Team for Swift 4 SDK Support  and was provided with https://github.com/AyoGitNg/isw-payment-sdk-ios/

The error module complied with Swift 3.1 cannot be imported in swift 3.2.3 is fixed!

But Now getting new errors:
1. 'Passport' is unavailable : cannot find the swift declaration for this class.
2. 'Payment'  is unavailable : cannot find the swift declaration for this class.
3. 'Pay'  is unavailable : cannot find the swift declaration for this class.
4.  'Purchase Response'  is unavailable : cannot find the swift declaration for this class.

And also i have followed the following steps:
1. Dragged the ​ PaymentSDK.framework file to the Embedded Binaries section of my app's TARGETS settings(General tab) and checked [copy items if needed].
2. import PaymentSDK

Please fix the issues with the SDK.

![screen shot 2018-01-06 at 11 30 38 am](https://user-images.githubusercontent.com/14849677/34637134-13f3e3cc-f2d5-11e7-9d16-85cdea527fbc.png)

______________

![screen shot 2018-01-06 at 11 17 39 am](https://user-images.githubusercontent.com/14849677/34637128-f1adfb54-f2d4-11e7-90a6-f49058744be3.png)

**Comment by rockinrohit92** [comment]
For Swift 4.0.2, use https://github.com/AyoGitNg/isw-payment-sdk-ios/releases/tag/v.0.0.0.5

**Comment by AyoGitNg** [comment]
Are you using a simulator or a real device.

The framework contains only arm and arm64 modules which are device modules. Clean the project and run on an actual device. Those errors should be gone.

**Comment by AyoGitNg** [comment]
@rockinrohit92, please use the updated Framework file [](https://github.com/AyoGitNg/isw-payment-sdk-ios/releases/download/v.0.0.0.5/PaymentSDK.framework.zip)

Also make sure you use the pod dependencies for swift 4.

**Comment by ajinkyashelar** [comment]
@AyoGitNg I am also facing the same problem. Same errors! Even in the Objective C sample code, the same errors are observed.  While when I tried in Swift Sample Demo it worked. Please fix it for running in an Objective C Project as well.

**Comment by AyoGitNg** [comment]
This is a repository that contains a sample working project with Swift 4.0.3 and Xcode 9.2

[https://github.com/AyoGitNg/IOSTest](url)

**Comment by rockinrohit92** [comment]
@AyoGitNg Thanks a lot! errors are gone now the issue was with the path referce of the Framework even i make sure ‘Copy items if needed’ is checked, Xcodes still makes refrence path refernce from dowloads directory.

**Comment by ajinkyashelar** [comment]
It's working fine with Swift 4.0 and Xcode 9.2 but when I am trying to integrate it into my existing project which uses Obj C majorly it is giving me below errors still. Can you please help me out on this? Thanks in advance. 

<img width="1172" alt="screen shot 2018-01-11 at 10 41 37 pm" src="https://user-images.githubusercontent.com/1098658/34837695-a0fa508a-f721-11e7-9f82-481f89a2620b.png">

**Comment by AyoGitNg** [comment]
@ajinkyashelar, we will test the sdk on an Obj C project and determine if we can reproduce this issue. If we do, an update that solves the issue will be released soon.

**Comment by AyoGitNg** [comment]
@ajinkyashelar, This has been reproduced. We are working on a fix

**Comment by AyoGitNg** [comment]
@ajinkyashelar, Please retry with the new framework file. Thank you.

**Comment by ajinkyashelar** [comment]
@AyoGitNg, Thanks for prompt response. Please send me the proper link to try the new framework I am unable to find it. 

Thanks in advance.

**Comment by AyoGitNg** [comment]
@ajinkyashelar ,
This is the link.

https://github.com/AyoGitNg/isw-payment-sdk-ios/releases/download/v.0.0.0.5/PaymentSDK.framework.zip
