### ISSUE TITLE
Not working with Xcode9.4

### ISSUE THREAD

**Issue by shroff-kandarp** [techquest/isw-payment-sdk-ios#39]
Error got:

PaymentSDK compiled with older version of Swift language (4.0) than previous files (unknown ABI version 0x06) file PaymentSDK' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Kindly provide both version for bitcode. 1 - by enabling bitcode and 2- by disabling bitcode.

I need bitcode to be enabled in my project but your framework built with "Disabling Bitcode". So xcode force me to disable bitcode for my project too. This is impossible to disable bitcode for some reason.

So, i am requesting to you that build your framework for xcode 9.4 with OR without bitcode.

**Comment by foomoto** [comment]
Hello, Please use the updated Frameworks file available here. https://github.com/techquest/isw-payment-sdk-ios/tree/master/Frameworks/Swift%204.1

Note this works only with the actual device.
Cheers!
