### ISSUE TITLE
Not compiling on Xcode Version 9.4.1 

### ISSUE THREAD

**Issue by dustyeric** [techquest/isw-payment-sdk-ios#40]
Getting the error below while compiling  the SDKtest project

Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1.2

**Comment by foomoto** [comment]
Hello, Please use the updated Frameworks file available here. https://github.com/techquest/isw-payment-sdk-ios/tree/master/Frameworks/Swift%204.1

Cheers!
